// <auto-generated />
namespace AboutCinema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class finally_initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(finally_initial));
        
        string IMigrationMetadata.Id
        {
            get { return "202005091027358_finally_initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
